### ISSUE TITLE
work env

### ISSUE THREAD

**Issue by robbschiller** [davidkpiano/movement#1]
What's your current setup for compilation and working on this?

I can pr with some "getting started" instructions...

**Comment by davidkpiano** [comment]
Hey @robbschiller, right now it's still in sandbox mode so it's very simple:
- `npm install`
- To run the sample demo file, `sass --watch scss/movement.scss:css/movement.css`
- To run the unit tests, `true-cli tests/tests.scss`

If you want to add a pull request with a gulpfile that autoprefixes and compiles `scss/movement.scss` and watches it, that would be awesome.

**Comment by robbschiller** [comment]
Great. Will do.

Any considerations for end use? Might be some items we don't want to include in a package-able branch?

**Comment by robbschiller** [comment]
:+1:
